window.routeConfigs = {

  "2": {title: "Ligne 2 • Orange", type: "lourd_orange",
    files: {currentShapes: "../GeoJSON/curr-cv_002.geojson", newShapes: "../GeoJSON/cv_002.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Côte-Vertu ⇋ Montmorency"},
    branchStyles: {
      "orange": {line: {color: "#D95700", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#D95700", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "REM": {title: "REM • Réseau express métropolitain", type: "lourd_rem",
    files: {currentShapes: "../GeoJSON/curr-A.geojson", newShapes: "../GeoJSON/cv_A.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Brossard ⇋ YUL Aéroport / Anse-à-l'Orme / Deux-Montagnes"},
    branchStyles: {
      "rem": {line: {color: "#73A400", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#73A400", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "cv_ouest": {title: "Côte-Vertu • Direction Ouest", type: "regulier",
    files: {currentShapes: "../GeoJSON/curr-cv-w.geojson", newShapes: "../GeoJSON/cv-w.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {121: "121 Ouest – Place Vertu", 
                      171: "171 Ouest – Station Côte-Vertu",
                      174: "174 Ouest – Air Canada",
                      177: "177 Ouest – Centre de transport Saint-Laurent",
                      378: "378 Ouest – YUL Aéroport",
                      380: "380 Ouest – Centre de transport Stinson"},
    branchStyles: {
      "1210002": {line: {color: "#781B7D", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#781B7D", fillOpacity: 1, shape: "circle"}},
      "1710018": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "1740004": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "1770008": {line: {color: "#8B469E", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#8B469E", fillOpacity: 1, shape: "circle"}},
      "3780003": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3800004": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "cv_est": {title: "Axe Côte-Vertu • Direction Est", type: "regulier",
    files: {currentShapes: "../GeoJSON/current-cv-e.geojson", newShapes: "../GeoJSON/cv-e.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {121: "121 Est – Saint-Michel / Sauvé", 
                      171: "171 Est – Station Henri-Bourassa",
                      174: "174 Est – Station Montpellier",
                      177: "177 Est – Thompson / Grimard",
                      378: "378 Est – Saint-Michel / Sauvé",
                      380: "380 Est – Centre de transport Anjou"},
    branchStyles: {
      "1210001": {line: {color: "#781B7D", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#781B7D", fillOpacity: 1, shape: "circle"}},
      "1710019": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "1740005": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "1770007": {line: {color: "#8B469E", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#8B469E", fillOpacity: 1, shape: "circle"}},
      "3780002": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3800005": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "hodge_west": {title: "Axe Hodge • Direction Ouest", type: "regulier",
    files: {currentShapes: "../GeoJSON/curr-hodge-w.geojson", newShapes: "../GeoJSON/hodge-w.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {124: "124 Sud – Station Vendôme", 
                      128: "128 Nord – Muir / Montpellier",
                      202: "202 Ouest – Station Fairview–Pointe-Claire",
                      380: "380 Est – Centre de transport Anjou"},
    branchStyles: {
      "1240011": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "1280023": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "2020019": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "3800005": {line: {color: "#000000", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#000000", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "hodge_est": {title: "Axe Hodge • Direction Est", type: "regulier",
    files: {currentShapes: "../GeoJSON/curr-hodge-e.geojson", newShapes: "../GeoJSON/hodge-e.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {124: "124 Nord – Station Côte-de-Liesse", 
                      128: "128 Sud – Station Côte-de-Liesse",
                      202: "202 Est – Station Côte-de-Liesse",
                      380: "380 Ouest – Station Côte-de-Liesse"},
    branchStyles: {
      "1240010": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "1280022": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "2020020": {line: {color: "#009EE0", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#009EE0", fillOpacity: 1, shape: "circle"}},
      "3800004": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``}
  
};
