window.routeConfigs = {
  
  "1": {title: "Ligne 1 • Verte", type: "lourd_verte",
    files: {currentShapes: "../GeoJSON/curr-001.geojson", newShapes: "../GeoJSON/001.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Angrignon ⇋ Honoré-Beaugrand"},
    branchStyles: {
      "verte": {line: {color: "#00B300", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#00B300", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "2": {title: "Ligne 2 • Orange", type: "lourd_orange",
    files: {currentShapes: "../GeoJSON/curr-002.geojson", newShapes: "../GeoJSON/002.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Côte-Vertu ⇋ Montmorency"},
    branchStyles: {
      "orange": {line: {color: "#D95700", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#D95700", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "4": {title: "Ligne 4 • Jaune", type: "lourd_jaune",
    files: {currentShapes: "../GeoJSON/curr-004.geojson", newShapes: "../GeoJSON/004.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Berri-UQAM ⇋ Longueuil-U.-de-S."},
    branchStyles: {
      "jaune": {line: {color: "#FFD900", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#FFD900", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "5": {title: "Ligne 5 • Bleue", type: "lourd_bleue",
    files: {currentShapes: "../GeoJSON/curr-005.geojson", newShapes: "../GeoJSON/005.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Snowdon ⇋ Anjou"},
    branchStyles: {
      "bleue": {line: {color: "#0095E6", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#0095E6", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "A1-A2": {title: "REM A1-A2 • Réseau express métropolitain", type: "lourd_rem",
    files: {currentShapes: "../GeoJSON/curr-A1-A2.geojson", newShapes: "../GeoJSON/A1-A2.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Brossard ⇋ YUL Aéroport Montréal-Trudeau"},
    branchStyles: {
      "remA2": {line: {color: "#73A400", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#73A400", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "A1-A3": {title: "REM A1-A3 • Réseau express métropolitain", type: "lourd_rem",
    files: {currentShapes: "../GeoJSON/curr-A1-A3.geojson", newShapes: "../GeoJSON/A1-A3.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Brossard ⇋ Anse-à-l'Orme"},
    branchStyles: {
      "remA3": {line: {color: "#73A400", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#73A400", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "A1-A4": {title: "REM A1-A4 • Réseau express métropolitain", type: "lourd_rem",
    files: {currentShapes: "../GeoJSON/curr-A1-A4.geojson", newShapes: "../GeoJSON/A1-A4.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Brossard ⇋ Deux-Montagnes"},
    branchStyles: {
      "remA4": {line: {color: "#73A400", weight: 7, opacity: 1},
          stop: {radius: 7, weight: 3, color: "#73A400", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "350": {title: "Ligne 350 • Verdun / LaSalle", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-350.geojson", newShapes: "../GeoJSON/350.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Frontenac", 
                      inbound: "Ouest – Centre de transport LaSalle"},
    branchStyles: {
      "3508888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3509999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "352": {title: "Ligne 352 • Centrale", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-352.geojson", newShapes: "../GeoJSON/352.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Sherbrooke", 
                      inbound: "Ouest – Terminus Lafleur / Newman"},
    branchStyles: {
      "3528888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3529999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "353": {title: "Ligne 353 • Lacordaire / Maurice-Duplessis", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-353.geojson", newShapes: "../GeoJSON/353.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Gare Rivière-des-Prairies", 
                      inbound: "Ouest – Station Frontenac"},
    branchStyles: {
      "3538888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3539999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "354": {title: "Ligne 354 • Des Sources / YUL Aéroport", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-354.geojson", newShapes: "../GeoJSON/354.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Place-des-Arts", 
                      inbound: "Ouest – Saint-Jean / Gouin"},
    branchStyles: {
      "3548888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3549999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "355": {title: "Ligne 355 • Pie-IX", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-355.geojson", newShapes: "../GeoJSON/355.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Carrefour Henri-Bourassa / Pie-IX", 
                      inbound: "Sud – Station Place-d'Armes"},
    branchStyles: {
      "3558888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3559999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "356": {title: "Ligne 356 • Sherbrooke / YUL Aéroport", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-356.geojson", newShapes: "../GeoJSON/356.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Frontenac", 
                      inbound: "Ouest – YUL Aéroport"},
    branchStyles: {
      "3568888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3569999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "357": {title: "Ligne 357 • Saint-Michel", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-357.geojson", newShapes: "../GeoJSON/357.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Saint-Michel / Henri-Bourassa", 
                      inbound: "Sud – Station Atwater"},
    branchStyles: {
      "3578888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3579999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "359": {title: "Ligne 359 • Papineau", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-359.geojson", newShapes: "../GeoJSON/359.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Henri-Bourassa / De Saint-Firmin", 
                      inbound: "Sud – Station Papineau"},
    branchStyles: {
      "3598888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3599999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "361": {title: "Ligne 361 • Saint-Denis", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-361.geojson", newShapes: "../GeoJSON/361.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Station Henri-Bourassa", 
                      inbound: "Sud – Station Place-d'Armes"},
    branchStyles: {
      "3618888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3619999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "362": {title: "Ligne 362 • Hochelaga / Notre-Dame", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-362.geojson", newShapes: "../GeoJSON/362.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – 100e Avenue / Bureau", 
                      inbound: "Ouest – Station Frontenac"},
    branchStyles: {
      "3628888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3629999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "363": {title: "Ligne 363 • Saint-Laurent", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-363.geojson", newShapes: "../GeoJSON/363.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Station Henri-Bourassa", 
                      inbound: "Sud – Station Place-d'Armes"},
    branchStyles: {
      "3638888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3639999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "364": {title: "Ligne 364 • Sherbrooke / Joseph-Renaud", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-364.geojson", newShapes: "../GeoJSON/364.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Centre de transport Anjou", 
                      inbound: "Ouest – Station Atwater"},
    branchStyles: {
      "3648888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3649999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "365": {title: "Ligne 365 • Du Parc", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-365.geojson", newShapes: "../GeoJSON/365.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Centre de transport Saint-Laurent", 
                      inbound: "Sud – Station Place-d'Armes"},
    branchStyles: {
      "3658888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3659999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "368": {title: "Ligne 368 • Édouard-Montpetit", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-368.geojson", newShapes: "../GeoJSON/368.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Frontenac", 
                      inbound: "Ouest – Station Côte-Vertu"},
    branchStyles: {
      "3688888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3689999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "369": {title: "Ligne 369 • Côte-des-Neiges", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-369.geojson", newShapes: "../GeoJSON/369.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Station Côte-de-Liesse", 
                      inbound: "Sud – Station Atwater"},
    branchStyles: {
      "3698888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3698887": {line: {color: "#000000", weight: 4, opacity: 1, dashArray: "5,10"},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3699999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "370": {title: "Ligne 370 • Rosemont", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-370.geojson", newShapes: "../GeoJSON/370.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Honoré-Beaugrand", 
                      inbound: "Ouest – Kildare / Westminster"},
    branchStyles: {
      "3708888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3709999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "371": {title: "Ligne 371 • Décarie", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-371.geojson", newShapes: "../GeoJSON/371.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Nord – Terminus Grenet / De Serres", 
                      inbound: "Sud – Station Papineau"},
    branchStyles: {
      "3718888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3719999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "372": {title: "Ligne 372 • Jean-Talon", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-372.geojson", newShapes: "../GeoJSON/372.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Gare Rivière-des-Prairies", 
                      inbound: "Ouest – Station Namur"},
    branchStyles: {
      "3728888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3729999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "3729998": {line: {color: "#6F6F6F", weight: 4, opacity: 1, dashArray: "5,10"},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "376": {title: "Ligne 376 • Brunswick / Centre-Ville", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-376.geojson", newShapes: "../GeoJSON/376.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Guy-Concordia", 
                      inbound: "Ouest – Gare Sainte-Anne-de-Bellevue"},
    branchStyles: {
      "3768888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3769999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "378": {title: "Ligne 378 • Sauvé / Côte-Vertu", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-378.geojson", newShapes: "../GeoJSON/378.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Saint-Michel / Sauvé", 
                      inbound: "Ouest – Station Pierrefonds–Roxboro"},
    branchStyles: {
      "3788888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3789999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},
  
  "380": {title: "Ligne 380 • Henri-Bourassa", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-380.geojson", newShapes: "../GeoJSON/380.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Centre de transport Anjou", 
                      inbound: "Ouest – Station Côte-de-Liesse"},
    branchStyles: {
      "3808888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3809999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "3809998": {line: {color: "#6F6F6F", weight: 4, opacity: 1, dashArray: "5,10"},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``},

  "382": {title: "Ligne 382 • Pierrefonds / Saint-Charles", type: "nuit",
    files: {currentShapes: "../GeoJSON/curr-382.geojson", newShapes: "../GeoJSON/382.geojson", 
            currentStops: "../GeoJSON/oldstops.geojson", newStops: "../GeoJSON/newstops.geojson"},
    directionLabels: {outbound: "Est – Station Namur", 
                      inbound: "Ouest – Gare Beaconsfield"},
    branchStyles: {
      "3828888": {line: {color: "#000000", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#000000", fillOpacity: 1, shape: "circle"}},
      "3829999": {line: {color: "#6F6F6F", weight: 4, opacity: 1},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "3829998": {line: {color: "#6F6F6F", weight: 4, opacity: 1, dashArray: "5,10"},
          stop: {radius: 4, weight: 3, color: "#6F6F6F", fillOpacity: 1, shape: "circle"}},
      "current": {line: {color: "#FFB350", weight: 10, opacity: 1},
          stop: {radius: 5, weight: 5, color: "#FFB350", fillOpacity: 1, shape: "circle"}}},
    changements: ``,
    pourquoi: ``}
  
};
